More improvements and fixes to cluster and vpc templates. documentation

diff --git a/kaws b/kaws
--- a/kaws
+++ b/kaws
@@ -1,18 +1,21 @@
 #!/bin/bash
 
 # Input Variables:
-# Env variable      | Command flag  | Required
-# ----------------------------------------------
-# KAWS_KEY_NAME     | --key-pair    |    YES
-# KAWS_DOMAIN_NAME  | --domain      |    YES
-# KAWS_BUCKET       | --bucket      |    YES
-# KAWS_AWS_PROFILE  | --profile     |    NO
-# KAWS_AWS_REGION   |               |    NO
-# KAWS_STACK_NAME   | --stack       |    NO
-# ----------------------------------------------
+# Env variable            | Command flag | Required
+# -------------------------------------------------
+# KAWS_KEY_NAME           | --key-pair   |   YES
+# KAWS_DOMAIN_NAME        | --domain     |   YES
+# KAWS_BUCKET             | --bucket     |   YES
+# KAWS_AWS_PROFILE        | --profile    |    NO
+# KAWS_AWS_REGION         |              |    NO
+# KAWS_STACK_NAME         | --stack      |    NO
+# KAWS_KUBERNETES_CLUSTER | --cluster    |    NO
+# -------------------------------------------------
 
+
+CONFIG_FILE=./kaws.conf
 # Input variables can be defined in the kaws.conf file
-[[ -f ./kaws.conf ]] && source ./kaws.conf
+[[ -f ${CONFIG_FILE} ]] && source ${CONFIG_FILE}
 
 # Default Values
 # ------------------------------------------------------------------------------
@@ -25,10 +28,12 @@ DEFAULT_PUBLIC_SUBNET_B_CIDR=10.0.102.0/24
 DEFAULT_PUBLIC_SUBNET_C_CIDR=10.0.103.0/24
 
 DEFAULT_AWS_PROFILE=default
-DEFAULT_STACK_NAME=Kubernetes
+DEFAULT_STACK_NAME=kaws
+DEFAULT_KUBERNETES_CLUSTER=${DEFAULT_STACK_NAME}kube
 
 : ${KAWS_AWS_PROFILE:=$DEFAULT_AWS_PROFILE}
 : ${KAWS_STACK_NAME:=$DEFAULT_STACK_NAME}
+: ${KAWS_KUBERNETES_CLUSTER:=$DEFAULT_KUBERNETES_CLUSTER}
 
 # Global Variables
 # ------------------------------------------------------------------------------
@@ -48,6 +53,8 @@ SCRIPT_NAME="$( basename "$0" )"
 
 # Enable debug with '--debug' parameter
 DEBUG=0
+# Enable deeper debug with '--debug2' parameter
+DEEP_DEBUG=0
 
 # UI functions
 # ------------------------------------------------------------------------------
@@ -260,7 +267,7 @@ check_bucket() {
     exit 1
   fi
 
-  aws --profile default s3 ls johandry-kube 2>/dev/null
+  aws --profile default s3 ls johandry-kube >/dev/null 2>&1
   if [[ $? -eq 0 ]]; then
     debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}KAWS_BUCKET${C_STD} is a valid S3 bucket (${KAWS_BUCKET})"
   else
@@ -289,6 +296,16 @@ setup() {
   fi
   stack_name=${KAWS_STACK_NAME}
 
+  if [[ -z ${KAWS_KUBERNETES_CLUSTER} ]]; then
+    error "kubernetes cluster name cannot be empty"
+    echo -e "Use flag ${C_YELLOW}--cluster${C_STD} to set the kubernetes cluster name"
+    usage 
+    exit 1
+  else
+    debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}KAWS_KUBERNETES_CLUSTER${C_STD} = ${KAWS_KUBERNETES_CLUSTER}" 
+  fi
+  kubernetes_cluster=${KAWS_KUBERNETES_CLUSTER}
+
   cd $SCRIPT_DIR
   mkdir -p vpc kube-aws 
   # mkdir -p iam addons
@@ -311,9 +328,8 @@ setup() {
 }
 
 clean() {
-  cd $SCRIPT_DIR
-  rm -rf vpc kube-aws 
-  # rm -rf iam addons
+  rm -rf $SCRIPT_DIR/vpc $SCRIPT_DIR/kube-aws 
+  # rm -rf $SCRIPT_DIR/iam $SCRIPT_DIR/addons
 }
 
 vpn_info() {
@@ -321,83 +337,155 @@ vpn_info() {
   echo -e "If you don't want to configure the Security Group manually, configure the server to use the port ${C_RED}12777${C_STD}"
 }
 
+was_init() {
+  # Pass '1' as argument to enable internal debug
+  dbg=${1:-0}
+  # Do not use Debug to debug this function, use the internal debug
+  int_dbg() {
+    (( ${dbg} )) && echo -e "${C_PURPLE}[DEBUG]${C_STD}  ${1}"
+  }
+
+  for f in kube-aws/cluster.yaml
+  do
+    int_dbg "'kubernetes_cluster' in $f"
+    grep -q 'kubernetes_cluster' $f && return 1
+  done
+ 
+  for f in kube-aws/cluster.yaml vpc/vpc.yaml # iam/iam.yaml iam/deploy addons/fluentd/fluentd-kubernetes-cloudwatch/fluentd.ds.yaml
+  do
+    int_dbg "'aws_region' in $f"
+    grep -q 'aws_region' $f && return 1
+  done
+
+  for f in kube-aws/cluster.yaml vpc/vpc.yaml 
+  do
+    int_dbg "'key_name' in $f"
+    grep -q 'key_name' $f && return 1
+  done
+
+  for f in kube-aws/cluster.yaml # iam/iam.yaml 
+  do
+    int_dbg "'hosted_zone_id' in $f"
+    grep -q 'hosted_zone_id' $f && return 1
+  done
+
+  for f in kube-aws/cluster.yaml vpc/vpc.yaml # addons/external-dns/external-dns.yaml
+  do
+    int_dbg "'domain_name' in $f"
+    grep -q 'domain_name' $f && return 1
+  done
+
+  for txt in ami_id my_ip VPC_CIDR PRIVATE_SUBNET_A_CIDR PRIVATE_SUBNET_B_CIDR PRIVATE_SUBNET_C_CIDR PUBLIC_SUBNET_A_CIDR PUBLIC_SUBNET_B_CIDR PUBLIC_SUBNET_C_CIDR
+  do
+    int_dbg "'${txt}' in vpc/vpc.yaml"
+    grep -q "${txt}" vpc/vpc.yaml && return 1
+  done
+  
+  # It was init'ed, return true
+  return 0
+}
+
 init() {
-  debug "Setting aws region"
+  debug "Initializing Cloudformation VPC stack ${C_YELLOW}${stack_name}${C_STD}:"
+
+  debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}kubernetes_cluster${C_STD} (${kubernetes_cluster})"
+  sed -i -e 's,kubernetes_cluster,'"$kubernetes_cluster"',g' kube-aws/cluster.yaml
+
+  debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}aws_region${C_STD} (${aws_region})"
   sed -i -e 's,aws_region,'"$aws_region"',g' kube-aws/cluster.yaml
   sed -i -e 's,aws_region,'"$aws_region"',g' vpc/vpc.yaml
   # sed -i -e 's,aws_region,'"$aws_region"',g' iam/iam.yaml
   # sed -i -e 's,aws_region,'"$aws_region"',g' iam/deploy
   # sed -i -e 's,aws_region,'"$aws_region"',g' addons/fluentd/fluentd-kubernetes-cloudwatch/fluentd.ds.yaml
 
-  debug "Setting key pair"
+  debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}key_name${C_STD} (${key_name})"
   sed -i -e 's,key_name,'"$key_name"',g' kube-aws/cluster.yaml
   sed -i -e 's,key_name,'"$key_name"',g' vpc/vpc.yaml
 
-  debug "Setting hosted_zone_id"
+  debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}hosted_zone_id${C_STD} (${hosted_zone_id})"
   sed -i -e 's,hosted_zone_id,'"$hosted_zone_id"',g' kube-aws/cluster.yaml
   # sed -i -e 's,hosted_zone_id,'"$hosted_zone_id"',g' iam/iam.yaml
 
-  debug "Setting domain_name"
+  debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}domain_name${C_STD} (${domain_name})"
   sed -i -e 's,domain_name,'"$domain_name"',g' kube-aws/cluster.yaml
   # sed -i -e 's,domain_name,'"$domain_name"',g' addons/external-dns/external-dns.yaml
   sed -i -e 's,domain_name,'"$domain_name"',g' vpc/vpc.yaml
 
-  debug "Setting ami_id"
+  debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}ami_id${C_STD} (${ami_id})"
   sed -i -e 's,ami_id,'"$ami_id"',g' vpc/vpc.yaml
 
-  debug "Setting allowed IP for VPN access SSH and Web ports"
+  debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}my_ip${C_STD} (${my_ip}) for VPN access SSH and Web ports"
   sed -i -e 's,my_ip,'"$my_ip"',g' vpc/vpc.yaml
 
+  debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}default CIDR values${C_STD}"
+  sed -i -e 's,VPC_CIDR,'"$DEFAULT_VPC_CIDR"',g' ./vpc/vpc.yaml
+  sed -i -e 's,PRIVATE_SUBNET_A_CIDR,'"$DEFAULT_PRIVATE_SUBNET_A_CIDR"',g' ./vpc/vpc.yaml
+  sed -i -e 's,PRIVATE_SUBNET_B_CIDR,'"$DEFAULT_PRIVATE_SUBNET_B_CIDR"',g' ./vpc/vpc.yaml
+  sed -i -e 's,PRIVATE_SUBNET_C_CIDR,'"$DEFAULT_PRIVATE_SUBNET_C_CIDR"',g' ./vpc/vpc.yaml
+  sed -i -e 's,PUBLIC_SUBNET_A_CIDR,'"$DEFAULT_PUBLIC_SUBNET_A_CIDR"',g' ./vpc/vpc.yaml
+  sed -i -e 's,PUBLIC_SUBNET_B_CIDR,'"$DEFAULT_PUBLIC_SUBNET_B_CIDR"',g' ./vpc/vpc.yaml
+  sed -i -e 's,PUBLIC_SUBNET_C_CIDR,'"$DEFAULT_PUBLIC_SUBNET_C_CIDR"',g' ./vpc/vpc.yaml
+
   find . -name "*-e" -exec rm -rf {} \;
-    
-  if [[ "$(aws --profile $aws_profile cloudformation describe-stacks --stack-name=$stack_name | jq -r '.Stacks[].StackStatus')" != "CREATE_COMPLETE" ]] > /dev/null 2>&1; then
-    debug "Setting default CIDR values in vpc.yaml"
-    sed -i -e 's,VPC_CIDR,'"$DEFAULT_VPC_CIDR"',g' ./vpc/vpc.yaml
-    sed -i -e 's,PRIVATE_SUBNET_A_CIDR,'"$DEFAULT_PRIVATE_SUBNET_A_CIDR"',g' ./vpc/vpc.yaml
-    sed -i -e 's,PRIVATE_SUBNET_B_CIDR,'"$DEFAULT_PRIVATE_SUBNET_B_CIDR"',g' ./vpc/vpc.yaml
-    sed -i -e 's,PRIVATE_SUBNET_C_CIDR,'"$DEFAULT_PRIVATE_SUBNET_C_CIDR"',g' ./vpc/vpc.yaml
-    sed -i -e 's,PUBLIC_SUBNET_A_CIDR,'"$DEFAULT_PUBLIC_SUBNET_A_CIDR"',g' ./vpc/vpc.yaml
-    sed -i -e 's,PUBLIC_SUBNET_B_CIDR,'"$DEFAULT_PUBLIC_SUBNET_B_CIDR"',g' ./vpc/vpc.yaml
-    sed -i -e 's,PUBLIC_SUBNET_C_CIDR,'"$DEFAULT_PUBLIC_SUBNET_C_CIDR"',g' ./vpc/vpc.yaml
-    #clean sed generated files
-    find . -name "*-e" -exec rm -rf {} \;
-  fi
 }
 
 deploy_vpc() {
-  echo -e "${C_BLUE}Creating CloudFormation VPC stack${C_STD}"
+  echo -e "${C_BLUE}Creating CloudFormation VPC stack ${C_YELLOW}${stack_name}${C_STD}"
 
   ROLE="kube-aws-vpc"
   STACK_FILE="vpc"
   SERVICE_NAME_PREFIX="k8s"
-  KUBERNETES_CLUSTER="demokube" #if you change this value, please also change the clusterName value in cluster.yaml
+  KUBERNETES_CLUSTER="${kubernetes_cluster}"
   STACK_PARAMS="ParameterKey=ServiceNamePrefix,ParameterValue=${SERVICE_NAME_PREFIX} ParameterKey=Role,ParameterValue=${ROLE} ParameterKey=KubernetesCluster,ParameterValue=${KUBERNETES_CLUSTER}"
   STACK_TAGS="Key=Role,Value=${ROLE}"
 
   debug "Validating template ${C_YELLOW}vpc/vpc.yaml${C_STD}"
-  aws cloudformation validate-template --template-body file://./vpc/vpc.yaml
+  aws cloudformation validate-template --template-body file://./vpc/vpc.yaml 2>&1 >/dev/null
+  if [[ $? -ne 0 ]]; then
+    error "invalid CloudFormation template ${C_YELLOW}vpc/vpc.yaml${C_STD}"
+    exit 1
+  fi
 
-  debug "Creating stack ${C_YELLOW}${stack_name}${C_STD}"
-  aws --region ${aws_region} cloudformation create-stack \
+  stackID=$(aws --region ${aws_region} cloudformation create-stack \
       --stack-name ${stack_name} \
       --template-body file://./vpc/vpc.yaml \
       --parameters ${STACK_PARAMS} \
       --capabilities CAPABILITY_IAM \
-      --tags ${STACK_TAGS}
+      --tags ${STACK_TAGS} | jq -r '.StackId')
+  if [[ $? -ne 0 ]]; then
+    error "failed to create stack ${C_YELLOW}${stack_name}${C_STD}"
+    exit 1
+  fi
+  echo -e "${C_BLUE}Creating stack ${C_YELLOW}${stack_name}${C_BLUE} with ID ${C_YELLOW}${stackID}${C_STD}"
 }
 
 create() {
   if [[ "$(aws --profile $aws_profile cloudformation describe-stacks --stack-name=$stack_name | jq -r '.Stacks[].StackStatus')" != "CREATE_COMPLETE" ]] > /dev/null 2>&1; then
+    status=$(aws --profile $aws_profile cloudformation describe-stacks --stack-name=$stack_name 2>/dev/null | jq -r '.Stacks[].StackStatus')
+    if [[ -n ${status} ]]; then
+      error "failed to create CloudFormation VPC stack ${C_YELLOW}${stack_name}${C_STD}, there is a stack with the same name"
+      echo
+      echo -e "Delete existing stack ${C_YELLOW}${stack_name}${C_STD} before execute the script again"
+      exit 1
+    fi
+
     deploy_vpc
 
     echo -e "${C_BLUE}Wait until the CloudFormation stack is created${C_STD}"
-    echo 
-    while [[ "$(aws --profile $aws_profile cloudformation describe-stacks --stack-name=$stack_name | jq -r '.Stacks[].StackStatus')" != "CREATE_COMPLETE" ]]
-      do sleep 2; printf ".";
+    while [[ "${status}" != "CREATE_COMPLETE" && "${status}" != "ROLLBACK_IN_PROGRESS" && "${status}" != "ROLLBACK_COMPLETE" ]]; do 
+      sleep 2; printf ".";
+      status=$(aws --profile $aws_profile cloudformation describe-stacks --stack-name=$stack_name | jq -r '.Stacks[].StackStatus')
     done
     echo ; echo
 
-    echo -e "${C_BLUE}CloudFormation VPC stack successfully created${C_STD}"
+    if [[ "${status}" == "CREATE_COMPLETE" ]]; then
+      echo -e "${C_BLUE}CloudFormation VPC stack successfully created${C_STD}"
+    else
+      error "failed to create CloudFormation VPC stack ${C_YELLOW}${stack_name}${C_STD}, check the error in the AWS console. Maybe there is other Kubernetes stack."
+      echo
+      echo -e "Delete stack ${C_YELLOW}${stack_name}${C_STD} before execute the script again"
+      exit 1
+    fi
   else
     echo -e "${C_BLUE}Stack ${stack_name} already created${C_STD}"
   fi
@@ -405,7 +493,7 @@ create() {
   echo -e "${C_BLUE}Stack ${stack_name} output:${C_STD}"
 
   VPN_DNS_RECCORD=$(aws --profile $aws_profile cloudformation describe-stacks --stack-name=$stack_name | jq -r '.Stacks[].Outputs[] | select(.OutputKey=="VpnDNSReccord") | .OutputValue')
-  echo -e "${C_RED}VPN_DNS_RECCORD:   ${C_GREEN}${VPN_DNS_RECCORD}${C_STD}"
+  echo -e "${C_RED}VPN_DNS_RECCORD:  ${C_GREEN}${VPN_DNS_RECCORD}${C_STD}"
 
   VPN_IP_ADDRESS=$(aws --profile $aws_profile cloudformation describe-stacks --stack-name=$stack_name | jq -r '.Stacks[].Outputs[] | select(.OutputKey=="VpnIpAddress") | .OutputValue')
   echo -e "${C_RED}VPN_IP_ADDRESS:   ${C_GREEN}${VPN_IP_ADDRESS}${C_STD}"
@@ -435,21 +523,51 @@ create() {
   echo -e "${C_RED}AWS_ACCOUNT_ID:   ${C_GREEN}${AWS_ACCOUNT_ID}${C_STD}"
 }
 
+was_init_install() {
+  # Pass '1' as argument to enable internal debug
+  dbg=${1:-0}
+  # Do not use Debug to debug this function, use the internal debug
+  int_dbg() {
+    (( ${dbg} )) && echo -e "${C_PURPLE}[DEBUG]${C_STD}  ${1}"
+  }
+
+  for txt in kubernetes_cluster kms_key_arn vpc_id vpc_cidr route_table_id private_subnet_a private_subnet_b private_subnet_c
+  do
+    int_dbg "'${txt}' in kube-aws/cluster.yaml"
+    grep -q "${txt}" kube-aws/cluster.yaml && return 1
+  done
+
+  # int_dbg "'aws_account_id' iam/iam.yaml"
+  # grep -q "aws_account_id" iam/iam.yaml && return 1
+  
+  # It was init installed, return true
+  return 0
+}
+
 init_install() {
   debug "Replacing the values from the CloudFormation VPC outputs"
+
+  debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}kms_key_arn${C_STD} (${kms_key_arn})"
   sed -i -e 's,kms_key_arn,'"$KMS_KEY_ARN"',g' kube-aws/cluster.yaml
+  debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}vpc_id${C_STD} (${vpc_id})"
   sed -i -e 's,vpc_id,'"$VPC_ID"',g' kube-aws/cluster.yaml
+  debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}vpc_cidr${C_STD} (${vpc_cidr})"
   sed -i -e 's,vpc_cidr,'"$VPC_CIDR"',g' kube-aws/cluster.yaml
+  debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}route_table_id${C_STD} (${route_table_id})"
   sed -i -e 's,route_table_id,'"$ROUTE_TABLE_ID"',g' kube-aws/cluster.yaml
+  debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}private_subnet_a${C_STD} (${private_subnet_a})"
   sed -i -e 's,private_subnet_a,'"$PRIVATE_SUBNET_A"',g' kube-aws/cluster.yaml
+  debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}private_subnet_b${C_STD} (${private_subnet_b})"
   sed -i -e 's,private_subnet_b,'"$PRIVATE_SUBNET_B"',g' kube-aws/cluster.yaml
+  debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}private_subnet_c${C_STD} (${private_subnet_c})"
   sed -i -e 's,private_subnet_c,'"$PRIVATE_SUBNET_C"',g' kube-aws/cluster.yaml
+  # debug "${C_GREEN}${I_CHECK}${C_STD}  ${C_YELLOW}aws_account_id${C_STD} (${aws_account_id})"
   # sed -i -e 's,aws_account_id,'"$AWS_ACCOUNT_ID"',g' iam/iam.yaml
   find . -name "*-e" -exec rm -rf {} \;
 }
 
 install() {
-  cd kube-aws
+  cd ${SCRIPT_DIR}/kube-aws
 
   echo -e "${C_BLUE}Generate credentials${C_STD}"
   kube-aws render credentials --generate-ca
@@ -473,8 +591,11 @@ install() {
 }
 
 destroy() {
-  echo -e "${C_YELLOW}This feature is not done yet${C_STD}"
-  echo -e "Login to the AWS Console, go to CloudFormation, select the stack ${C_YELLOW}${KAWS_STACK_NAME}${C_STD}, expand the Action button and select ${C_RED}Delete Stack${C_STD}"
+  echo -e "${C_YELLOW}Destroying the kube-aws CloudFormation stacks${C_STD}"
+  cd ${SCRIPT_DIR}/kube-aws
+  AWS_PROFILE=$aws_profile kube-aws destroy 2>/dev/null
+  echo -e "${C_YELLOW}Destroying the CloudFormation stack ${C_YELLOW}${stack_name}${C_STD}"
+  aws --profile $aws_profile cloudformation delete-stack --stack-name ${stack_name}
 }
 
 # Usage function
@@ -482,10 +603,10 @@ destroy() {
 usage() {
   echo -e "${C_GREEN}KAWS${C_STD} is a script for setting up a Kubernetes cluster on AWS"
   echo
-  echo "Usage:"
+  echo -e "${C_WHITEBOLD}Usage:${C_STD}"
   echo "  ${SCRIPT_NAME} [ command ] [ flags ]"
   echo
-  echo "Commands:"
+  echo -e "${C_WHITEBOLD}Commands:${C_STD}"
   echo "  help                      Print this help message"
   echo "  init                      Initialize all the required files"
   echo "  create                    Create the clusters to install Kubernetes. Includes the init phase"
@@ -494,16 +615,41 @@ usage() {
   echo "  clean                     Delete all created files"
   echo "  destroy                   Destroy the Kubernetes cluster"
   echo
-  echo "Flags:"
+  echo -e "${C_WHITEBOLD}Flags:${C_STD}"
   echo "  -h | --help               Print this help message"
-  echo "  --debug                   Enable debug mode"
+  echo "  --debug                   Enable debug mode. By default is disabled"
   echo "  --profile <aws profile>   AWS profile to use. Default ${DEFAULT_AWS_PROFILE}"
   echo "  --stack <stack name>      Stack name. Default ${DEFAULT_STACK_NAME}"
+  echo "  --cluster <cluster name>  Kubernetes cluster name. Default ${DEFAULT_KUBERNETES_CLUSTER}"
   echo 
-  echo -e "${C_YELLOW}Required Flags${C_STD}"
+  echo -e "${C_YELLOW}Required Parameters as Flags${C_STD}"
   echo "  --key-pair <key pair>     AWS Key Pair"
   echo "  --domain <domain name>    Domain name in Route 53"
   echo "  --s3 <s3 bucket name>     AWS S3 bucket name"
+  echo 
+  echo -e "${C_YELLOW}Required Parameters as Environment Variables${C_STD}"
+  echo "  KAWS_KEY_NAME=<key pair>       AWS Key Pair"
+  echo "  KAWS_DOMAIN_NAME=<domain name> Domain name in Route 53"
+  echo "  KAWS_BUCKET=<s3 bucket name>   AWS S3 bucket name"
+  echo 
+  echo "Use the required flags or the required environment variables to enter"
+  echo "the required parameters. If both are used, the flags have preference."
+  echo -e "It's allowed to define the environment variables in the file ${C_WHITEBOLD}${CONFIG_FILE}${C_STD}"
+  echo 
+  echo -e "${C_WHITEBOLD}Example of ${CONFIG_FILE}${C_STD}"
+  echo "  KAWS_KEY_NAME=kube-keypair"
+  echo "  KAWS_DOMAIN_NAME=mycompany.com"
+  echo "  KAWS_BUCKET=mycompany-kube-bucket"
+  echo "  # Optional:"
+  echo "  KAWS_AWS_PROFILE=mycompany"
+  echo "  KAWS_AWS_REGION=us-west-2"
+  echo "  KAWS_STACK_NAME=mycompany"
+  echo "  KAWS_KUBERNETES_CLUSTER=mycompany-kube-cluster"
+  echo 
+  echo -e "${C_WHITEBOLD}Quick Start${C_STD}"
+  echo "  $0 install --stack mycompany"
+  echo "  $0 destroy"
+  echo "  $0 clean"
 }
 
 # Main code
@@ -517,9 +663,13 @@ while (( "$#" )); do
     ;;
     --debug ) DEBUG=1
     ;;
+    --debug2 ) DEEP_DEBUG=1
+    ;;
     --profile ) KAWS_AWS_PROFILE=$2 ; shift
     ;;
     --stack ) KAWS_STACK_NAME=$2 ; shift
+    ;;
+    --kube-name ) KAWS_KUBERNETES_CLUSTER=$2 ; shift
     ;;
     --key-pair ) KAWS_KEY_NAME=$2 ; shift
     ;;
@@ -535,7 +685,7 @@ while (( "$#" )); do
     ;;
     init-install ) action=init-install
     ;;
-    destroy ) destroy ; exit 0
+    destroy ) action=destroy
     ;;
     clean ) clean ; exit 0
     ;;
@@ -562,18 +712,19 @@ case ${action} in
     init
   ;;
   create ) 
-    init
+    # if was initialized, do not run init or will overwrite any custom modification
+    was_init ${DEEP_DEBUG} || init
     create
   ;;
   init-install )
-    init
-    create
     init_install
   ;;
-  install ) 
-    init
+  install )
+    # if was initialized, do not run init or will overwrite any custom modification
+    was_init ${DEEP_DEBUG} || init
     create
-    init_install
+    # if was initialized for install, do not run init_install or will overwrite any custom modification
+    was_init_install ${DEEP_DEBUG} || init_install
     install
   ;;
   destroy )
